"""Add question_count to interview

Revision ID: 10e9f86e2be6
Revises: c8a77e15dc3e
Create Date: 2026-06-21 15:53:27.462385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e9f86e2be6'
down_revision = 'c8a77e15dc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_job', sa.String(length=150), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    # ### end Alembic commands ###
