"""Update InterviewAnswer model

Revision ID: a403d1c81326
Revises: 917b921e57bd
Create Date: 2026-06-24 18:24:07.375549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a403d1c81326'
down_revision = '917b921e57bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gemini_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gemini_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('eye_contact_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('head_pose_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('speech_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('filler_words', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pause_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answers', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('pause_count')
        batch_op.drop_column('filler_words')
        batch_op.drop_column('speech_rate')
        batch_op.drop_column('head_pose_score')
        batch_op.drop_column('eye_contact_score')
        batch_op.drop_column('gemini_feedback')
        batch_op.drop_column('gemini_score')

    # ### end Alembic commands ###
