"""Add AI analysis fields to interview answer

Revision ID: b3c022eb6d65
Revises: 68ca7738e7df
Create Date: 2026-06-26 22:16:35.336898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c022eb6d65'
down_revision = '68ca7738e7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('voice_fluency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('voice_pace', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('face_detection', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answers', schema=None) as batch_op:
        batch_op.drop_column('face_detection')
        batch_op.drop_column('voice_pace')
        batch_op.drop_column('voice_fluency')
        batch_op.drop_column('voice_score')

    # ### end Alembic commands ###
