"""Add target job and experience level

Revision ID: db231236c5fa
Revises: 2fc33b2930d8
Create Date: 2026-06-20 18:43:47.778502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db231236c5fa'
down_revision = '2fc33b2930d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_job', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('experience_level')
        batch_op.drop_column('target_job')

    # ### end Alembic commands ###
